{% set name = "napari-aicsimageio" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-aicsimageio-{{ version }}.tar.gz
  sha256: 40a683a1e91f20f8d7ebe3b44d250134b4a352ee1d907b5ed0a03d675b81a685

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - pytest-runner >=5.2
  run:
    - aicsimageio >=4.1
    - fsspec
    - napari >=0.4.11
    - napari-plugin-engine >=0.1.4
    - python >=3.8

test:
  imports:
    - napari_aicsimageio
    - napari_aicsimageio.core
    - napari_aicsimageio.in_memory
    - napari_aicsimageio.out_of_memory
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AllenCellModeling/napari-aicsimageio
  summary: AICSImageIO for napari. Multiple file format reading directly into napari using pure Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - JacksonMaxfield
